### Exercice 1:

Write a function that takes a string, and two indexes (integers), and returns a slice of that string as well as the length of the string.
Call the function, and store the results in two variables

In [6]:
def para(string,a,b):
    slice=string[a:b+1]
    lenght=len(string)
    
    return slice,lenght
para("hajar lamtaai",2,6)
    

        
    

('jar l', 13)

### Exercice 2:

1. Write a function that takes two arguments, and returns the sum of the two.
2. Call the function with the values 1 and 2.1, then check the type of the result.
3. Call the function with the values False and 2, then check the type of the result.

In [17]:
#Declare the function
def sum(x,y):
    return x+y

#Call with the values 1 and two
type(sum(1,2.1))
#Check the type of the result
type(sum(False,2))

int

### Exercice 3:

Write a function that takes a string and returns a dictionary containing character frequency.

*example*

    string sample: 'test'
    
    expected result: {'t':2, 'e':1, 's':1}

In [24]:
#Declare the function
def dictio(string):
    L=[]
    
    for i in range (len(string)):
        if string[i] not in L:
            L.append(string[i])
    A={}
    for i in range(len(L)):
        A[L[i]]=(string.count(L[i]))
    return A

dictio("hajar")
        


{'h': 1, 'a': 2, 'j': 1, 'r': 1}

### Exercice 4:

Given two lists, iterate both lists simultaniously, such the first list would display item in original order and the second list in reverse order

*example*:

In [3]:
from lib import print_orl #this is a lib you dont have access to
print_orl([1,2,3],[1,2,3])

1 3
2 2
3 1


In [29]:
def iter(A,B):
    n= len(A)
    for i in range(n):
        print(A[i], B[n-i-1])
iter([1,2,3],[1,2,3,])

1 3
2 2
3 1


### Exercice 5:

Given two 2d arrays, stack them horizontally.

*example:*

In [4]:
import numpy as np

#The input
a = np.ones((1, 10)).reshape(2, -1)
b = np.zeros((1, 10)).reshape(2, -1)


#Try to print input
print(a)
print(b)

#concatenate horizontally
#output shoul look like:     array([[1., 1., 1., 1., 1., 0., 0., 0., 0., 0.],
#                                   [1., 1., 1., 1., 1., 0., 0., 0., 0., 0.]])

print(np.concatenate((a,b), axis=1))


[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[1. 1. 1. 1. 1. 0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1. 0. 0. 0. 0. 0.]]


### exercice 6:

Create the following patterns using the bellow arrays a and b, and numpy functions:

In [5]:
a = np.arange(3)
b = np.ones((3,3,3))
print(a)
print(b)

#output1 the following array: array([0, 0, 0, 1, 1, 1, 2, 2, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2])
#...

#output2 the follwing array: array([[[1., 2., 3.],
#                                    [1., 2., 3.],
#                                    [1., 2., 3.]],

#                                    [[1., 2., 3.],
#                                    [1., 2., 3.],
#                                    [1., 2., 3.]],

#                                    [[1., 2., 3.],
#                                    [1., 2., 3.],
#                                    [1., 2., 3.]]])

#output3 array([[1., 1., 1., 1., 1., 1., 1., 1., 1.],
#                [1., 1., 1., 1., 1., 1., 1., 1., 1.],
#                [1., 1., 1., 1., 1., 1., 1., 1., 1.]])



[0 1 2]
[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]
